version: '3'
services:
  codeceptjs:
    image: codeception/codeceptjs
    environment:
      - CODECEPT_ARGS=--reporter mochawesome
    volumes:
      - .:/tests
    container_name: docker-nightmare
